project:
  type: book

book:
  title: "A Short Introduction to R for Probability"
  author: "Enrico Wegner"
  date: "1-28-2024"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-r-calculator.qmd
    - 03-variables-indexing.qmd
    - 03-02-structures.qmd
    - 04-clean-code.qmd
    - 05-loops.qmd
    - 06-conditionals.qmd
    - 07-functions.qmd
    - 08-random-numbers.qmd
    - 09-monte-carlo-simulation.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



